### PR TITLE
Android production fixes.

### PR DESCRIPTION
**Pull request by deathbaba**

### CODE REVIEW

**Comment by dkorolev** [comment]
Will take a look in ~10 hours, @deathbaba, would that be OK with you?

**Comment by deathbaba** [comment]
@dkorolev We are planning to release it next week. Be ready with a server-side :)

**Comment by deathbaba** [comment]
Yep, check it when you have time.

**Comment by deathbaba** [comment]
@dkorolev did you write small daemon to unpack gzipped cereal files from folder/subfolders on a server?

**Comment by dkorolev** [comment]
Ah, this pull request comments thread is where your gunzip question was :-)

Yes and no -- receive, but not unzip. https://github.com/KnowSheet/Sandbox/blob/master/FileReceiver/test.cc

**Comment by dkorolev** [comment]
Added a bunch of per-commit comments. The only one I'd prefer to get taken care of prior to merging this PR is the one that has to do with the "truth only on the first time" comment.

Thanks,
Dima

**Comment by deathbaba** [comment]
Does your ScanDir use recursion? Correct nginx configuration for production will create some folder hierarchy for received files, to avoid millions of files in the same folder.

You can also check this cool tool: http://linux.die.net/man/1/inotifywatch

**Comment by deathbaba** [comment]
PTAL

**Pull request merged**
