### PR TITLE
Always force uploading of the current data.

### PR DESCRIPTION
**Pull request by deathbaba**
It worked previously only in the cases when no any finalized statistics files were stored in the queue.

### CODE REVIEW

**Comment by dkorolev** [comment]
Didn't we discuss it previously that this is a bad idea?

**Comment by deathbaba** [comment]
Our business logic _needs_ this case - to log first user launch, before he decide to uninstall the app.

The worst bug issue in the FSQ with it’s current architecture is demonstrated below:
```
Alohalytics::LogEvent(“userHasInstalledTheApp”);
Alohalytics::ForceUpload();
```
These 2 lines of code, if second goes immediately after the first, does not guarantee that this even will be delivered to the server (it can be still in the memory queue).

The only solution I can think about to resolve this case is to use queue itself for passing “ForceUpload” events - we were discussing it in December’14.

**Comment by dkorolev** [comment]
Didn't we agree that there is only one event -- first install -- that
requires `ForceUpload(true)`?

Thanks,
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by deathbaba** [comment]
No - in general, we need to get the data in the most convenient way for us (at least once a day or more frequently) and for the user (consuming less battery, preferably over WiFi, when system wakes up every app in the background specifically to help them communicate with the net, all apps at once).
Don’t know how to implement it with only FSQ internal logic - here ForceUpload comes.

**Comment by dkorolev** [comment]
If I remember it right, assuming the queue is empty, the current logic is:

1) upload the data right away as long as the device is in WFi, and
2) when the device is in mobile internet, start sending the data as it
reaches some relatively small age (~15 minutes?) or some small size
(~100KB?).

Also, If I recall correctly, the hard cutoff time is 24 hours: even in case
of connection errors, when retry logic kicks in, the maximum time interval
for which data sending will be suspended is 24 hours.

You can look up the above constants in the code. If the estimates I cite
are not way off, they look fine for me to keep in production. And we
already had the issue of DoS-ing ourselves, which was fixed by eliminating
"forced" uploads.

What exactly are we discussing?

PS: It's 3am and I have a flight tomorrow. Going to sleep soon.


Thanks,
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by deathbaba** [comment]
I’m telling you about a bug in the current MQ/FSQ arch which reproduces in production environment:
```
fsq->PushMessage(msg);
fsq->ForceProcessing(true);
```
sometimes does not send msg to the server, because it is still on the different thread and did not come into FSQ uploader yet.

**Comment by dkorolev** [comment]
Ah, if this is the issue, just have `ForceProcessing` send the event
through the same in-memory message queue. That would solve it like a charm.

Again: Your currently proposed solution is a way to DoS yourself. Which
already happened recently.

Thanks,
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by deathbaba** [comment]
Don’t remember any issues with DoSing, only with broken packets.
If you are speaking about iOS logs I’ve sent you (about exponential delay), they were from development environment, not in production.
And even for production environment I don’t see any risks for now.

**Comment by dkorolev** [comment]
I don't endorse this change, but you are free to push it.

Thanks,
Dima

Thanks,
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by deathbaba** [comment]
@dkorolev PTAL

**Comment by dkorolev** [comment]
The way you read the file with `::fgets()` will break each *line* on the `'\0'` character. Since you only need the binary output plus the code, why not use `::fread()`` in the loop, not `::fgets()`?

**Comment by dkorolev** [comment]
(Also, I'm not happy these two changes -- `curl` and `ForceUpload()` -- ended up in the same pull request. Am happy to merge either of both of them though.)

**Comment by deathbaba** [comment]
Thanks for mentioning about fgets! Fixed it. @dkorolev PTAL

**Comment by dkorolev** [comment]
LGTM the curl/file part. Hope the `ForceUpload()` logic does what it should; we'd need to chat more about it some day soon.

Merging now.

Thanks,
Dima

**Pull request merged**
